name: Build

on:
  workflow_call:
    inputs:
      versionSuffix:
        required: false
        type: string
        default: ci
      packShipCandidate:
        required: false
        type: boolean
        default: false

env:
  SAMPLE_PATH: ./samples/TagHelperPack.Sample/TagHelperPack.Sample.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build package & sample site

    steps:
    - uses: actions/checkout@v3
    
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        global-json-file: "./global.json"
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Create build number
      run: |
        now=$(date +'%Y%m%d')
        buildNumber=$now.$GITHUB_RUN_NUMBER
        echo "BUILD_NUMBER=$buildNumber" >> $GITHUB_ENV
        echo "$buildNumber"

    - name: Build
      run: dotnet build --configuration Release --no-restore -p:BuildNumber=$BUILD_NUMBER -p:SourceRevisionId=$GITHUB_SHA -p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build

    - name: Publish sample (net472)
      run: dotnet publish $SAMPLE_PATH --framework net472 --configuration Release --no-build --verbosity normal

    - name: Publish sample (net6.0)
      run: dotnet publish $SAMPLE_PATH --framework net6.0 --configuration Release --no-build --verbosity normal

    - name: Publish sample (net7.0)
      run: dotnet publish $SAMPLE_PATH --output artifacts/samplesite --framework net7.0 --runtime linux-x64 --self-contained --configuration Release --verbosity normal
      
    - name: Pack (ci)
      run: dotnet pack --configuration Release --output artifacts/ci --verbosity normal -p:BuildNumber=$BUILD_NUMBER -p:SourceRevisionId=$GITHUB_SHA -p:ContinuousIntegrationBuild=true

    - name: Pack (ship candidate)
      if: ${{ inputs.packShipCandidate }}
      run: dotnet pack --configuration Release --output artifacts/ship --verbosity normal -p:BuildNumber=$BUILD_NUMBER -p:SourceRevisionId=$GITHUB_SHA -p:ContinuousIntegrationBuild=true -p:IsShipCandidate=true

    - name: Upload artifacts (packages)
      uses: actions/upload-artifact@master
      with:
        name: nupkg
        path: artifacts/**/*.nupkg
        retention-days: 5
    
    - name: Upload artifacts (sample site)
      uses: actions/upload-artifact@master
      with:
        name: samplesite
        path: artifacts/samplesite
        retention-days: 5
