name: PRs

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    name: Build & Test PR
    uses: ./.github/workflows/_build.yml
    with:
      versionSuffix: ci
