name: PRs

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build & Test PR
        uses: ./.github/workflows/_build.yml
        with:
          versionSuffix: ci
