name: Release

on:
  workflow_dispatch:
    inputs:
      runId:
        description: The run ID of the CI workflow to release NuGet artifacts from
        required: true
        type: string

jobs:
  push-package:
    name: Push packages to nuget.org from 
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ inputs.runId }}
          workflow_conclusion: success
          name: nupkg
      
      - name: Print package version
        run: |
          _filepath="$(find ./ship -iname '*.nupkg')"
          _filename="${_filepath##*/}"
          _pkgname="${_filename%.*}"
          _version="${_pkgname##TagHelperPack.}"
          echo "${_version}"
